### ISSUE TITLE
Bitwarden not recognising Edge Canary browser on Android

### ISSUE THREAD

**Issue by danmac** [bitwarden/android#1394]
## Describe the Bug

Bitwarden doesn't recognise the new Edge Canary browser on Android as a web browser.

## Steps To Reproduce

1. Download Edge Canary from Play Store
2. Open any website with a password field
3. Click Auto-fill with Bitwarden

## Expected Result

Bitwarden searches for the web site you are viewing and displays the result for that web site

## Actual Result

Bitwarden searches for com.microsoft.emmx.canary or something similar, you then have to manually search for the web site

## Environment

- Device: Pixel 4 XL
- Operating system: Android 11
- Build Version RQ2A.210405.005
- Is this a Beta release? N

**Comment by xiaoyuin** [comment]
Hello @contribucious , I tested with newest Bitwarden (2.10.0) and it still doesn't work for Edge canary. Could you please take a look again if the PR really works? :)

**Comment by wight554** [comment]
> Hello @contribucious , I tested with newest Bitwarden (2.10.0) and it still doesn't work for Edge canary. Could you please take a look again if the PR itself really works or some other code changes are needed as well? :)

Can confirm it's still broken

**Comment by contribucious** [comment]
@xiaoyuin (@wight554) Hello. Really sorry, could not answer before (very busy at the moment).

:arrow_right: Yes, the PR of @laymanZ is correct regarding the addition of browser support (I mean … the package name is **com.microsoft.emmx.canary** and the "resource-id" is indeed equal to **url_bar** as visible on the screenshot n°1 below). So, [this line](https://github.com/bitwarden/mobile/blob/afed18908bcd89065275ccf1a7f4fc6be3a646a7/src/Android/Accessibility/AccessibilityHelpers.cs#L59) for ex. is indeed correct.

For my part, enabling "Auto-fill Service" (i.e. Autofill Framework) + "Use Accessibility" (i.e. Accessibility Service) + "Use Draw-Over" in Bitwarden settings, I have no problem to use it, see screenshots [n°2](https://user-images.githubusercontent.com/4764956/121185533-7203c080-c866-11eb-8cf1-5b6f155e3526.jpg) and [n°3](https://user-images.githubusercontent.com/4764956/121185570-7a5bfb80-c866-11eb-98d8-69bc5dd8a0a1.jpg) (**additional note:** github.com was successfully detected).

**BUT …** only the accessibility service seems to be used (see screenshot [n°4](https://user-images.githubusercontent.com/4764956/121193133-dc6c2f00-c86d-11eb-9142-2209ae8dc007.jpg)), unlike the latest stable version of Chrome which is the 91.0.4472.88 (see screenshot [n°5](https://user-images.githubusercontent.com/4764956/121193156-e1c97980-c86d-11eb-8065-a765ebc4cd3e.jpg)).

:arrow_right_hook: The situation should be further analyzed then (to see if the problem lies with Bitwarden or Edge Canary, etc.). See with the team therefore (@mportune-bw, @cscharf, …), specifying the precise type of your problem (i.e. what you mean exactly by "doesn't work"), whether you use Autofill Framework, Accessibility Service or both, if the "Draw-Over" permission has been given (in Bitwarden settings > "Auto-fill Services"), your device info (model, …) and version of Android / Edge Canary / Bitwarden, etc. (open another issue if necessary). Same remark for you @wight554. :wink:
&nbsp;

## My context
- Edge Canary 93.0.910.0 (the latest version to date)
- Bitwarden 2.10.0 (the latest stable version)*
- Samsung Galaxy J5 2017, on Android 9.

\* Tested both with Autofill Framework + Accessibility Service and with Accessibility Service only.
&nbsp;

## Screenshot(s)

**Screenshot n°1**

![Microsoft_Edge_Canary](https://user-images.githubusercontent.com/4764956/121175072-f0f2fc00-c85a-11eb-9c18-980862c9d7ba.png)
_Edge Canary 93.0.910.0._

**Comment by danmac** [comment]
Thanks for the extra work on this, I can confirm that mine shows the same behaviour as your screenshots. Let me know if you need someone to test anything.

**Comment by wight554** [comment]
in my case I can't see keyboard autofill like in other browsers, accessibility overlay works just fine

**Comment by xiaoyuin** [comment]
Appreciate for the investigation and detailed reply. By doesn't work I meant neither accessibility service or draw-over was enabled. But it doesn't matter, we have also done some research and now I'm quite sure that you have done everything right. The problem is on the Edge side. Thank you again for the help and all the efforts you have made. :)

**Comment by contribucious** [comment]
@xiaoyuin My pleasure! :thumbsup:

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1394
