### ISSUE TITLE
Android App Ignores Ports in Hostnames

### ISSUE THREAD

**Issue by gregg098** [bitwarden/android#1620]
### Steps To Reproduce

1) Add a site with a hostname and a port and set the match to "Host"

For example, for my Synology NAS (Diskstation), a local domain in Bitwarden that works fine on Windows is:
http://diskstation.services.lan:5000 (Host Matching)

2) Open http://diskstation.services.lan:5000 on Chrome on Android
3) Bitwarden will **not** find any matches.
4) Manually search for "diskstation", select the proper entry. Then get popup to autofill, autofill and save (I think that's the wording), etc.
5) If I hit "autfill and save," it fills in the user/pass fields and moves on.
6) Now, my Diskstation site in Bitwarden has two sites:
- http://diskstation.services.lan:5000 (host)
- http://diskstation.services.lan (default match)

This will now find the site in BW every time, but now all my other home services on the *.services.lan domain will also have a "Diskstation" entry, which I was trying to avoid.

### Expected Result

Expect auto search to be able to find the correct site just as it would in Windows

### Actual Result

Many home services are the exact same domain, just different ports. Instead of having to scroll through a giant list of them, I set each entry to "Host" so that it matches everything exactly. No issues with this approach in Windows, but Android never finds the BW entry and wants a basic domain stripped of ports.

### Operating System

Android

### Operating System Version

11

### Device

Samsung Galaxy S21+

### Build Version

2.14.0 (3977)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Sim0nW0lf** [comment]
I am having the same and another related issue!
The browser Extentions work well, only the app has this problem...

I set my whole app to "Host", just like my browser extentions and saw other problems as well.
If I take your site as example:
http://diskstation.services.lan will work just fine
http://www.services.lan does not work

That means if the app is in "Host" mode, then no website without custom subdomain or with port will work.
(Not sure if that is entirely true, didn't test enough but that's my theory)
Hopefully that will be fixed! Thanks for your awesome development! :)

**Comment by Sim0nW0lf** [comment]
Everything is working for me now!
Running the Bitwarden App Beta V2.14.2

Maybe the stable app only has this issue? I don't know.
Is it working for you as well?

**Comment by gregg098** [comment]
Signed up for beta, but didnt get an app update. Still have the same issue on stable.

**Comment by Sim0nW0lf** [comment]
Which app version are you running at the moment?

**Comment by gregg098** [comment]
Version: 2.14.2 (4005)

**Comment by lcasale** [comment]
I have this issue on 2.16.2

**Comment by Sim0nW0lf** [comment]
For me it is also broken again.

URI Match Detection "base domain" works
but
URI Match Detection "host" which I am using is not working

**Comment by redxtech** [comment]
I am still getting this issue on version 2022.6.1 (4795).

I'm wondering if this is at all on the radar of the team?

**Comment by KevoM** [comment]
Same on android 12 and Bitwarden version 2023.1.0

**Comment by Kartoffl** [comment]
same on android 12, bitwarden version 2023.3.2 (6098)

**Comment by 2PieceCombo** [comment]
I have an issue that seems to be along these same lines.

I have a service running on https://10.13.1.100
My entry was set to: https://10.13.1.100/login
Browser works fine, but on mobile is says "no item found for 10.13.1.100" (using android btw)
Ive tried changing the URI match to base domain, host, and starts with, none of them worked on mobile.
If i change the entry to https://10.13.1.100/ it still does not work, but if I remove the / at the end, it suddenly does recognize it. However I run dozens of internal services on the same IP but different ports. The android version completely ignores entries if there is anything following the IP address, regardless if it actually matches. 

This means that I can't use any of my saved logins on my internal services, unless I manually search for them. This is incredibly frustrating because mobile is already the least convenient to use, and this issues makes it nearly unusable.

**Comment by jufy111** [comment]
I'm also having the same issue. Autofill works without issue on desktop but on mobile it won't auto fill HOST:IP correctly, regardless of the match settings.

**Comment by Meinnick** [comment]
same on android 13, bitwarden version 2023.8.0 (7466)

**Comment by weilah** [comment]
I'm facing the same problem on Android (bitwarden version 2023.10.0 (8257)). I tried chrome and brave with same results. The port gets somehow lost in the way when trying to match URIs. I tried "starts with..." and "host", but bitwarden only sees the local IP and not the port.

If I press add login then the URI is shown without the port

**Comment by sv87411** [comment]
Same issue here on 2023.10.0 (8257) (Android 13).

With multiple home hosted apps often with the same home domain/host hosting apps on multiple ports with multiple logins Bitwarden needs to recognise the port as a part of the URI.

In the Bitwarden docs it says port is considered to be part of the host for matching purposes so why doesn't it behave like this on Android?

**Comment by TheColtron** [comment]
Exact same in v2024.3.0. I've had this problem for ages, and only finally tried to pin down the problem today. 

No issues with the browser extension, and this happens on all auto fill modes (inline and whatever the normal one is called).

Here's how it works. URIs like `http://{IP}:{Port}`:
- Fail to auto fill on Host 
- Fail to auto fill on Starts With
- Fail to auto fill on Regex
- Successfully auto fills when using base domain

Why is it a problem?:
- Saving a login on a `http://{IP}:{Port}` page (via the + button or "Auto fill & save") doesn't capture the port in the URI. Users will then edit the URI and add the port to fix this, but some users will also change the match type at the same time (since hostname matching, according to its name, should not be used in this case).
- The docs describe the extension behavior, but the mobile app behaves differently 

So hopefully that helps point in the right direction of a fix. For anyone having this issue, you can workaround it by using base domain matching on the full socket address. I've only been on mobile since writing, so I don't know if this will mess up matching on the extension version though.

**Comment by MossyGreen** [comment]
Same issue here on v2024.4.0

It's disappointing to see that the issue has persisted since 2021

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1620
