### ISSUE TITLE
iOS: "Share file" only lists photos, no videos

### ISSUE THREAD

**Issue by kpcyrd** [bitwarden/android#1725]
### Steps To Reproduce

1. Open the bitwarden app on iOS
2. Click on "Send"
3. Click on "Add send"
4. Click on "Select file"
5. It shows "Photos, Camera, Browse", click on Photos

### Expected Result

Both videos and photos are listed and I can pick either of them

### Actual Result

It shows my camera roll but only photos are listed, all videos are missing

### Operating System

iOS

### Operating System Version

15.1

### Build Version

2.15.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by semiligneous** [comment]
Hi Bitwarden product and dev team - any feedback on this one? I really needed to use Send today to quickly send a video clip securely and was frustrated and disappointed to discover that it was not possible! 


workaround:

Open video in iOS Photos > share > Save to Files. Create Send in Bitwarden > Browse > Files > upload. Delete duplicate copy from Files.

Perhaps this was a deliberate decision, since videos are often over 100mb? If so, I think the sender should get to make that choice themselves.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1725
