### ISSUE TITLE
Login failure when vault locked with Firefox 

### ISSUE THREAD

**Issue by YannBrrd** [bitwarden/android#1799]
### Steps To Reproduce

1. Go to any logon form known to bitlocker using Firefox, with vault locked
2. Click on 'unlocking bitwarden'
3. Choose user password from bitwarden
4. Well nothing
5. Refresh page and get bitwarden filling login form 

### Expected Result

Bitwardwn should fill login after unlocking

### Actual Result

Bitwarden disappear after unlocking, comes back when refreshing page

### Operating System

Android

### Build Version

2.16.2

### Beta

- [ ] Using a pre-release version of the application.

**Comment by pinpontitit** [comment]
I was about to post that issue because I was so annoyed since many days, and I just discovered yours. 
Thats exactly what I am experiencing.
Its horrible because if I want to use autofill I need to let unlock my vault...
I hope it will be solved soon because if autofill doesnt work properly in conjunction with automatic lock, that could be a reason for me to switch password manager.

**Comment by JSteitz** [comment]
Have nearly the same issue. Just that even a page refresh does not bring back the autofill.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1799
