### ISSUE TITLE
Not prompting to add a new login to vault

### ISSUE THREAD

**Issue by ltmatch** [bitwarden/android#1841]
### Steps To Reproduce

Create a new account or sign [](https://github.com/bitwarden/browser/issues/1620) in to an account that is not being stored in your vault

### Expected Result

A pop up at the bottom of the screen prompting me to save my password to bitwarden with the options “save password,” “never for this website,” or “not now”
![0474DFC8-E977-42CE-BE07-CDE08EEEC346](https://user-images.githubusercontent.com/101428430/158026299-71a4adab-af09-4981-93e7-e6cc3f00c916.jpeg)

### Actual Result

No prompt is shown.

### Additional Context

Similar to this desktop browser extension issue: https://github.com/bitwarden/browser/issues/1620

### Operating System

iOS

### Operating System Version

15.3.1

### Device

iPhone SE 2nd Generation (2020)

### Build Version

Version: 2.16.2 (1434)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by ltmatch** [comment]
It is quite similar to this browser extension issue: https://github.com/bitwarden/browser/issues/1620

**Comment by SergeantConfused** [comment]
Hi @ltmatch,

While Bitwarden can offer to save the last-used credentials on certain clients, we do not currently support and offer that on iOS; What you have described is the expected behaviour on iOS. I cannot promise you if/when that would be incorporated into our iOS client at this stage.

I hope you find this helpful. Please do not hesitate to get in touch with us using this form: https://bitwarden.com/contact/ if you have any questions.


All the best,

**Comment by ltmatch** [comment]
@SergeantConfused this is not what I am talking about. This is when logging in to an account that is not stored in the vault at all. As stated in the original issue report, it is similar to this browser issue: https://github.com/bitwarden/browser/issues/1620

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1841
