### ISSUE TITLE
Cannot save new login if personal ownership is disabled

### ISSUE THREAD

**Issue by oglodyte** [bitwarden/android#1874]
### Steps To Reproduce

1. disable personal ownership in the organization policy
2. go to any site (cnn.com) in mobile Safari and try to create new login using Bitwarden extension

### Expected Result

Login saved

### Actual Result

Extension hands on saving new login
New login is not saved

### Additional Context

Extension does not offer to set the collection for the new login and it is mandatory when personal ownership is disabled. 

Proposed Solution(s):
1. Add the ability to select collections for the new item
2. Add the ability to define default collection for the new items (per organization, for the person or both).  This collection should be applied to new items by default if not specified otherwise.

### Operating System

iOS

### Operating System Version

15.4.1

### Device

iPhone 13 Pro Max

### Build Version

12.17.0 (1626)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Gerardv514** [comment]
Just found this here. An issue was discovered when Single Organization & Remove Indivudaul Vault options were turned on for an organization. We reported here [https://github.com/bitwarden/clients/pull/4808](url) an issue with the browser extension. 

I have also determined that same user when using iOS Safari browser attempting to save a new item, when they use the share sheet they do not have any access to any collections. When they save the item they just get a spinning circle and "saving." I believe the problem is due to them not having the ability to choose which collection to save the item to. If they exit out and go into the Bitwarden iOS app, they are able to save the item there since they are able to choose which collection to save the item to.

@oglodyte has created this more than a year and half ago and still hasn't been fix.

**Comment by Gerardv514** [comment]
Does anyone need more of a step by step breakdown to replicate this? Is there not enough information provided to reproduce?

I’m looking to do whatever I can to have this resolved. If this can’t be reproduced please advise and maybe a better explanation can be provided.

**Comment by Gerardv514** [comment]
@dwbit @trmartin4 @kspearrin 

if you can reproduce this, can you at least put this on the teams radar. I have a feeling this hasn’t been looked at..at all but I can surely reproduce. Additionally there was some work similar to this setup, done on the browser extension side.

**Comment by SergeantConfused** [comment]
Hi everyone,

Thank you for your reports. I was able to reproduce this behaviour and I have flagged it to our Engineering team.

If you wish to add any further information, such as screenshots or screen recordings, please feel free to do so at any time - our Engineering team will be happy to review them.

Thank you again,

**Comment by Gerardv514** [comment]
> Hi everyone,
> 
> Thank you for your reports. I was able to reproduce this behaviour and I have flagged it to our Engineering team.
> 
> If you wish to add any further information, such as screenshots or screen recordings, please feel free to do so at any time - our Engineering team will be happy to review them.
> 
> Thank you again,

@SergeantConfused is this on their list to fix? Any expectation of when this would start being worked on , this year ? 2024? 2025?

Thank you

**Comment by Gerardv514** [comment]
Any update on this???

**Comment by Gerardv514** [comment]
@SergeantConfused is this moving along????

**Comment by Gerardv514** [comment]
@bitwarden-devops-bot any update?

**Comment by Gerardv514** [comment]
@djsmith85 any update on this?

**Comment by Gerardv514** [comment]
I just lost 2 clients due to this. Fucking mess

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/1874
