### ISSUE TITLE
iOS / iPadOS: Viewing vault item causes crash

### ISSUE THREAD

**Issue by Private-Fragrance** [bitwarden/android#2131]
### Steps To Reproduce

_(I'm new to GitHub; someone said I should report this here --I don't see an iOS client option for bugs...?)_

This affected both iPhone and iPad apps. I had one entry that I could not view as it would immediately cause the app to crash.

Luckily I was able to view it in the web vault so I could fix it.

Somewhat inconclusive but still useful research:

1. When I cloned the item, the clone crashed too
2. The item had a custom field with an emoji -- on a hunch I removed the emoji. (Call this Custom Field A)
3. The item also had two custom fields with identical titles, on a hunch I changed one of them. (They had identical titles but different content.) (Call these Custom Field B and Custom Field C)
4. Those two things made it so the cloned item would launch properly. I then made the same changes to the original entry and it launches properly now. Problem solved.
5. ...what's inconclusive is that removing ONLY the emoji or removing ONLY the duplicate custom field title did not fix the issue. It was only when I removed both.

### Expected Result

View vault item

### Actual Result

Unable to view vault item due to app crashing when accessing that specific item

### Operating System

iOS

### Operating System Version

iOS 16.x & iPadOS 15.x

### Web Browser

Safari

### Build Version

2022.9.1 (2147)

**Comment by djsmith85** [comment]
@Private-Fragrance Thank you for the report and I have moved it to the bitwarden/mobile repository.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2131

**Comment by Greenderella** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so.

I have items created as early as April 2020, some with attachments and some without, and some with custom fields and some without. All of these items can be viewed, cloned, launched, and edited (including adding and removing emojis/custom fields) as expected on iPadOS 17.6.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by Greenderella** [comment]
Hi @Private-Fragrance,

> My “corrupted” entry had a bunch of custom Text fields but one had ~300 characters without spaces, ~350 with spaces. It had a bunch of uninteresting characters but it did have unbroken strings of **hyphens**,

This issue seems similar to the one described here: https://github.com/bitwarden/mobile/issues/3330 🤔

Could you please try to replicate this problem using the beta version as well? You can join the beta program and download the app following these steps: https://community.bitwarden.com/t/about-the-beta-program/39185

Given the recent updates to the beta builds, it would be beneficial to verify if the issue persists with the latest version.

Thanks for your assistance, and I eagerly await your feedback!
