### ISSUE TITLE
[Android] When account it set to maximum 2,000,000 PBKDF iterations cannot log on

### ISSUE THREAD

**Issue by credfeto** [bitwarden/android#2295]
### Steps To Reproduce

Prerequisites:
* KDF iterations is set to 2,000,000

1. Enter email address
2. Enter password
3. log on
4. See Error "Username or password is incorrect"

Note if KDF iterations is reduced on web to say 300,000 then the error does not appear

### Expected Result

Be able to log in (note can log in with the web vault and the chrome add in on desktop)

### Actual Result

Error "Username or password is incorrect"

### Operating System

Android

### Operating System Version

Android 13

### Device

Onepus 10 Pro

### Build Version

2022.11.0 (5580)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Greenderella** [comment]
Hi there,

Thank you for your report! We are able to reproduce this issue. The error should be more specific, maybe hint the user that the problem is their device being unable to cope with their current PBKDF iterations settings, and not an incorrect user/master password.  

If you wish to add any information/screenshot/recording or so, please do it here and our engineering team will review it.

**Comment by jawz101** [comment]
My phone gives an error that the operation was cancelled when I set the iterations to 600,001

**Comment by martijk** [comment]
I’m unable to log in on iOS after changing the number of iterations to the new default of 600,000.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2295
