### ISSUE TITLE
android user failing to save changed settings for unlocking with biometrics (similar to IOS issue)

### ISSUE THREAD

**Issue by briggzzz** [bitwarden/android#2307]
### Steps To Reproduce

4. Click on '...'
Go to settings.
click on unlock with biometrics or Unlock with PIN code
Change to on.
Next time using the app it reverts to being off for either setting.

### Expected Result

To have these app setting stay "on" after choosing them to do so.

### Actual Result

Later in the day, after the app times out, it reverts to "off" for both of the settings listed above.

### Operating System

Android

### Operating System Version

android 13

### Device

Google pixel 6a

### Build Version

2022.11.0 (5580)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Greenderella** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so, unlock settings persist on my Android 12 device with Bitwarden Version 2023.1.0. Will you first try uninstalling the application, resetting your device (Power Off/On) and re-installing? 

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists after the reinstallation with the latest update (2023.1.0), please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
