### ISSUE TITLE
Autofill prompts do not appear when using Opera with the URL bar set at the bottom of the interface.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/android#2365]
### Steps To Reproduce

1. Open Opera.
2. Navigate to Vimeo's Login webpage (https://vimeo.com/log_in).
3. Tap on the (Email) or (Password) field.

### Expected Result

To see an Autofill prompt.

### Actual Result

No Autofill prompt is shown.

### Screenshots or Videos

N/A.

### Additional Context

If the URL bar is set at the top of the interface (Settings > Appearance > Address bar > Top), the Accessibility Autofill prompt shows up at the Vimeo Login webpage.

### Operating System

Android

### Operating System Version

12.

### Device

Samsung Note10+.

### Build Version

2023.1.0 (5786).

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Greenderella** [comment]
Hi,

Thank you for your report! This issue has flagged to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by arifszn** [comment]
Autofill does not work in my case even if the address bar is on top. However, I have noticed two things and also a found workaround to enable autofill on opera mobile. 

My autofill service settings: 

<img src="https://user-images.githubusercontent.com/45073703/236761678-ad62c69b-f73f-423e-84b9-e052a27fdde1.jpg" width="30%"/>

- When I go to a login page, the autofill popup does not show up. But if I open my notification bar and close it, the bitwarden icon shows up and offers to select credentials from the currently active URL. Here you can see, the URL is empty or --. That's why the autofill popup does not appear as Bitwarden is receiving an empty URL from the browser.

https://user-images.githubusercontent.com/45073703/236770743-5737efb7-e51c-4756-8d15-592b70573b1b.mp4


<img src="https://user-images.githubusercontent.com/45073703/236772317-edfc23c1-c775-4b7b-b68a-ceb0a8377a72.jpg" width="30%"/>

- If I click the login field and then open the browser URL tab, bitwarden can match the correct URL and offers suggestions. You have to try 2-3 times sometimes.

https://user-images.githubusercontent.com/45073703/236771254-b05c0c3c-5a97-4da6-b4d2-9ebe5d138766.mp4
