### ISSUE TITLE
Fairemail autofill bug

### ISSUE THREAD

**Issue by john-crane-69** [bitwarden/android#2471]
### Steps To Reproduce

1. Import a pgp key into openkeychain (Opensource openpgp client for Android) 
2. Go to Fairemail (Opensource Mail client) 
3. Try to decrypt an email that is encrypted with PGP key by pressing on the lock icon
4. Open the auto fill prompt to fill in the password
5. Add in your fingerprint and select the password
6. Select a password from the list

### Expected Result

The password should be filled in when selecting from the list

### Actual Result

The password doesn't fill in and it shows as a glitch refresh

### Screenshots or Videos

https://user-images.githubusercontent.com/15282798/231743018-933160c4-edb0-4a2e-9a07-338962153cb5.mp4

### Additional Context

It should be noted that I contacted the developers of both Fairemail and openkeychain and they both confirmed that the issue is with bitwarden and not their software since it worked with other password managers

The issue is displayed in the video provided

### Operating System

Android

### Operating System Version

Android 13

### Device

Pixel 7 Pro

### Build Version

2023.3.2 (6098) 

### Beta

- [ ] Using a pre-release version of the application.

**Comment by josbarros** [comment]
Interesting, I'm having the exact same problem but with K-9 Mail instead.... The root cause is probably the same as the OP's case. Would you like me to provide anything?

**Operating System**
Android

**Operating System Version**
LineageOS 18.1 microG (Android 11)

Device
Nokia 6.1

Build Version
2023.4.0 (6203)

**Comment by Adedamola-Aina** [comment]
Hi @josbarros 

We appreciate you letting us know of this issue. Due to the nature of autofill issues, we track them internally using different Forms depending on the platform:

mobile: https://docs.google.com/forms/d/e/1FAIpQLScMopHyN7KGJs8hW562VTzbIGL4KcFnx0wJcsW0GYE1BnPiGA/viewform

browser extension: https://docs.google.com/forms/d/e/1FAIpQLSfkxh1w6vK8fLYwAbAAEVhvhMAJwfFNDtYtPUVk1y5WTHvJmQ/viewform

In this case, we will go ahead and file an autofill report for you with the information you added here.

In the future, if you encounter any other page or app that doesn't autofill as expected, please avoid opening a new GitHub issue and go directly to the corresponding form.

This issue will now be closed. 

Thanks!

**Comment by matty-r** [comment]
I have this same issue. Super frustrating. Just last week it worked once, but I haven't been able to reproduce it. I've filed another report through the forms.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2471
