### ISSUE TITLE
iOS Auto-fill gives identifies different potential credentials than from within Bitwarden

### ISSUE THREAD

**Issue by abuchanan920** [bitwarden/android#2551]
### Steps To Reproduce

1. Create a credential for a subdomain site like a.test.com
2. Create a credential for a subdomain site like b.test.com
3. Set match detection for both to be of type Host
4. Go to one of the sites
5. Click the Key icon in the lower corner
6. You will see both credentials in the popup
7. Click on "Bitwarden..." in the popup
8. You will see only the correct credential (as expected)

### Expected Result

I would expect the popup to respect the matching rules in both places (not just the second)

### Actual Result

Matching rules seem to be ignored in the logic that create the entries for the popup. It seems to only care about matching the domain name.

### Operating System

iOS

### Operating System Version

16.5

### Device

iPad Pro

### Build Version

2023.4.0 (3303)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by MarcelVersteeg** [comment]
I would like to add an additional issue with the list in the popup (at least on my iPhone SE2020 running iOS 16.6):
When I have a single login item with multiple hosts added to the item, all matched on complete host, the single match I need is only given when the first host in the list is loaded, otherwise I get a list of all matches on domain.

So, let say there are three sub domains and a main domain: a.example.com, b.example.com, c.example.com, example.com
I have a login vault item A, that holds the password for a.example.com and b.example.com (happens to be the same) in that order, a login vault item C, that holds the password for c.example.com, and a login vault item Main, that holds the password for example.com. The matching rules for all hosts are set to "Host".

Now perform the following scenarios:
1. Open site a.example.com: The popup correctly indicate to use the username/password for a.example.com and logging in is a simple click. Correct behavior.
2.  Open site b.example.com: I need to click on the "key" icon, because the credentials for the main domain are suggested and after clicking the "key" icon, I see the passwords for a.example.com, c.example.com and example.com, but **NOT** for b.example.com (I know I can use the credentials for a.example.com, but it is not intuitive).
3. Open site c.example.com: The popup correctly indicate to use the username/password for c.example.com and logging in is a simple click. Correct behavior.
4. Open site example.com: The popup correctly indicate to use the username/password for example.com and logging in is a simple click. Correct behavior.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2551
