### ISSUE TITLE
Bitwarden doesn't lock when (Use accessibility) Autofill Service is activated

### ISSUE THREAD

**Issue by JulioM18** [bitwarden/android#2602]
### Steps To Reproduce

1. Go to settings and set Vault timeout > "On app restart" and Vault Timeout Action > "Lock"
2. Go to settings and enable Auto-fill Services > "Use Accessibility"
3. Restart the app

### Expected Result

Bitwarden should lock when restarting the app and ask for the password or PIN

### Actual Result

It doesn't lock

### Operating System

Android

### Operating System Version

Android 10

### Device

Samsung galaxy a6+

### Build Version

Version: 2023.5.0 (6330)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by TroyBW** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team. Technically, the issue seems to be that the Bitwarden app is not restarting when the Accessibility autofill feature is enabled.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2602
