### ISSUE TITLE
isConnected failed: ETIMEDOUT (Connection timed out)

### ISSUE THREAD

**Issue by Gooberpatrol66** [bitwarden/android#2870]
### Steps To Reproduce

1. enter email
2. click selfhosted
3. enter server
4. click continue

### Expected Result

Works, like in browser extension

### Actual Result

Exception message: failed to connect to <server>(port 443) from <client> (port 46162) after 86400000ms: isConnected failed: ETIMEDOUT (Connection timed out)

### Operating System

Android

### Build Version

2023.10.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by TroyBW** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error may be a network configuration issue, but it is hard to say for certain.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2870
