### ISSUE TITLE
Bitwarden collects the package name of the Huawei browser instead of the webpage URL.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/android#2887]
### Steps To Reproduce

1. Install Huawei browser.
2. Attempt to perform Auto-Fill.

### Expected Result

For the webpage URL to be relayed to Bitwarden.

### Actual Result

The package name is relayed to Bitwarden, so it would not match with an existing vault item.

### Screenshots or Videos

N/A.

### Additional Context

N/A.

### Operating System

Android

### Operating System Version

12

### Device

Samsung Note10+

### Build Version

2023.10.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by Vstory** [comment]
This is common on Android, as is other password stuffing software.

**Comment by bbervel** [comment]
Xiaomi 12 lite too - collect "com.mi.globalbrowser" instead of site name
Also can not collect app name and match it with app name like on IOS

**Comment by Hoanui** [comment]
Same thing on Waterfox (Firefox branch).

POCO X3 NFC

Android 12

MIUI 14

The screenshot shows what happens if you try to add a login from the waterfox browser.

![Screenshot_2023-12-23-12-58-20-221_com x8bit bitwarden](https://github.com/bitwarden/mobile/assets/16444007/3fd099ca-c647-49d4-b336-de50b35e967f)

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2887
