### ISSUE TITLE
Folders name issue

### ISSUE THREAD

**Issue by nightznero** [bitwarden/android#2935]
### Steps To Reproduce

for now I only noticed that "🧖🏼‍♂️" doesnt fix to sort

### Expected Result

Should sort A-Z

### Actual Result

Sort Folders as on screen most of time but sometimes it doesn't

### Screenshots or Videos

![Screenshot_20240111_122130](https://github.com/bitwarden/mobile/assets/61750641/e669595a-20d6-4afb-ad17-2cf9ef134302)

### Operating System

Android

### Device

S20 Ultra

### Build Version

Newest 2024.1.0

### Beta

- [ ] Using a pre-release version of the application.

**Comment by NovaSilentium** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/ 

Please sign up on our forums and search to see if this request already exists (https://community.bitwarden.com/signup). If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Note that the “Closed as not planned” status is for internal tracking purposes only, please do not hesitate to send us your suggestions to the forum.

Thanks!

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/2935
