### ISSUE TITLE
vault search on iOS displays wrong results when selecting passkey

### ISSUE THREAD

**Issue by pkinerd** [bitwarden/android#3242]
### Steps To Reproduce

4. Click on '...'

### Expected Result

Text/search in Bitwarden popup when selecting passkey on IOS should show items in vault that match the text entered

### Actual Result

Other seemingly unrelated or no results are displayed

### Screenshots or Videos

Searches during passkey selection pop-up:

![IMG_9398](https://github.com/bitwarden/mobile/assets/169779439/20d0399c-9968-45fb-b54b-ec3516f0b26b)
![IMG_9397](https://github.com/bitwarden/mobile/assets/169779439/3ce4c553-5b1b-4acb-bfc2-0b356f3e3cdd)
![IMG_9396](https://github.com/bitwarden/mobile/assets/169779439/dca5397f-bfd5-447f-a011-9596edf610eb)

final search (by launching app and searching manually) - shows correct results

![IMG_9399](https://github.com/bitwarden/mobile/assets/169779439/fbdbbf0c-e7b8-4ecb-aad4-4176fe9567f5)

### Additional Context

screen shots show a vault item of “passkeys.io test” exists but isn’t displayed for search of “pass” or “passk” but is displayed for searches of “.io”… weirdly the search shows other results that don’t contain the searched phrase.

the final screen shot (time 7.32) shows that in the Bitwarden app - the search does display the one and only item matching “passk”.

### Operating System

iOS

### Operating System Version

17.4.1

### Device

iPhone15 Pro

### Build Version

© Bitwarden Inc. 2015-2024  Version: 2024.4.2 (7528)

### Beta

- [ ] Using a pre-release version of the application.

**Comment by lf-** [comment]
Can reproduce on 2024.5.1 (7674) on iPadOS 17.4.1 on iPad Air 4th generation.

Steps: go to https://passkeys.io and register on desktop. It might do the same if you register from iPad, I didn't try.

Pull out your iOS device and go to https://passkeys.io and click the sign in with passkey button, which brings up this dialog (which, unlike what you're about to see, *does* work properly if you just hit continue; but there's no way to deal with multiple passkeys with that).

![IMG_0079](https://github.com/bitwarden/mobile/assets/6652840/57160f8b-06fc-4dd6-89b9-3e0bbe01eaed)

Click "other sign-in options"

![IMG_0080](https://github.com/bitwarden/mobile/assets/6652840/be32f3f1-8f11-4a3b-ab55-25d542e96161)

Pick "Bitwarden", which brings up a search that doesn't work; enter "passkeys.io" in the search box, which *should* have results because there *is* an entry as evidenced by previous screens:

![IMG_0081](https://github.com/bitwarden/mobile/assets/6652840/e0b80637-7ae8-4574-b696-1d808a6d8c3b)

To add bonus frustration, clicking an irrelevant result (since it shows results that don't even have passkeys! It should not do that) returns a non-descriptive error:

![IMG_0082](https://github.com/bitwarden/mobile/assets/6652840/17c01eec-b579-4e52-856f-40d50a5bd1a6)

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/3242
