### ISSUE TITLE
Autofill and other issues

### ISSUE THREAD

**Issue by likevi9528** [bitwarden/android#3354]
### Steps To Reproduce

I found two issues on Autofill, one issue on "My vault" page.

**Autofill Issues:**
_Turn on "Auto-fill" -> "Auto-fill services"
Use Gboard
500+ items
Use vaultwarden selfhost
Defalut URI match detection: Base domain_

1. When using Chrome(126) and Firefox(127.0.1) app to log in to a website, there is a high probability that the Bitwarden fill icon will not be displayed on Gboard. The probability of Chrome not displaying the autofill icon is higher than Firefox.
2. When logging into a website, if the Gboard displays a fill icon, clicking on the displayed "Bitwarden beta" will take about 5 seconds before jumping to the Bitwarden beta app. There is also a chance that after jumping to the APP, all items will be displayed, and it will take about 5 seconds to display the item to log in to the website.

**"My vault" Issue:**
After unlocking the app, there is a small chance that it will stay in the loading interface for a long time. As shown in the following figure **pic1**

**"Setting" -> "Other" -> "Sync now" Issue:**
The "Sync now" of the Bitwarden beta app seems to be partial synchronization, while the "Sync now" of the Bitwarden old version is full synchronization. I prefer to use full synchronization.

### Expected Result

As mentioned above

### Actual Result

As mentioned above

### Screenshots or Videos
pic1: ![81ebeabc67615d7fa7c4c6a2935ead3](https://github.com/bitwarden/android/assets/81839775/f138ec8c-fa28-4714-95d6-c061b5e831f7)

### Build Version

2024.6.1

### Environment Details

- Device: Redmi K30
- OS: Android 12

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by BBGhub** [comment]
Hi there!

We appreciate you letting us know of this issue. Due to the nature of autofill issues, we track them internally using different Forms depending on the platform:

mobile: https://docs.google.com/forms/d/e/1FAIpQLScMopHyN7KGJs8hW562VTzbIGL4KcFnx0wJcsW0GYE1BnPiGA/viewform

browser extension: https://docs.google.com/forms/d/e/1FAIpQLSfkxh1w6vK8fLYwAbAAEVhvhMAJwfFNDtYtPUVk1y5WTHvJmQ/viewform

In the future, if you encounter any other page or app that doesn't autofill as expected, please avoid opening a new GitHub issue and go directly to the corresponding form.

This issue will now be closed. 

Thanks!
