### ISSUE TITLE
Favicons missing that work in browser extension

### ISSUE THREAD

**Issue by Norsze** [bitwarden/android#3382]
### Bitwarden Beta

- [X] Using the new native Bitwarden Beta app. Note: Bugs found in the legacy .NET apps should be reported in bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

Add any of the following websites as a new item in the vault (these are the ones I have found so far):

- [overdrive.com](https://www.overdrive.com/)
- [sj.se](https://www.sj.se/)
- [experis.se](https://www.experis.se/en)
- [mangaupdates.com](https://www.mangaupdates.com/)

### Expected Result

It will show a favicon just like in the browser extensions and web app for the added sites.

### Actual Result

It doesn't show the favicon, instead shows a globe icon.

### Build Version

2024.6.0 (10746)

### Environment Details

- Device: Samsung Galaxy s22+ 
- OS: Android 14, ONE UI 6.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by BBGhub** [comment]
With regard to the favicons, please first make sure that the site has a compatible one by using any of the online finder tools (like https://realfavicongenerator.net/favicon_checker or http://www.faviconfinder.com/). 

If it does, please attempt to refresh the vault item that is not showing the favicon by adding https://icons.bitwarden.net/www.YOUR_URL.com/icon.png?refresh=123 as your new URI 1. Remember to replace the “YOUR_URL” part with the actual correct URL, as this will prompt Bitwarden to try to pull the favicon from scratch:

It is worth noting that this can also happen when the website stores its favicon at a non-standard location, and can also be potentially caused by our own servers (CDN) as we had received reports about that, and we are looking into them. 

If the steps above did not assist you in resolving this, please bear with us while we continue to examine this matter internally, and hopefully we'll address it in the near future.

We're sorry about this inconvenience, and we thank you for your patience.

 
 



Kind Regards,

Ben



[Subscribe to the Bitwarden Newsletter](https://bitwarden.com/newsletter-subscribe/)



Follow Bitwarden

[Reddit](https://www.reddit.com/r/Bitwarden/) | [Twitter](https://twitter.com/bitwarden) | [GitHub](https://github.com/bitwarden) | [Facebook](https://www.facebook.com/bitwarden) | [LinkedIn](https://www.linkedin.com/company/bitwarden1)

On Thu, Jun 27 at 8:54 PM , GitHub/Jira/Asana - Bitwarden <asana2zapier2freshdesk@bitwarden.com> wrote: 
A new issue has been filled on Jira, and it needs to be vetted: https://bitwarden.atlassian.net/browse/PM-9353

The full information can be found in GitHub: https://github.com/bitwarden/android/issues/3382
--------------------------------------------------------------------------------

Add any of the following websites as a new item in the vault (these are the ones I have found so far):,It will show a favicon just like in the browser extensions and web app for the added sites.,It doesn't show the favicon, instead shows a striped ball icon.,No response,No response,2024.6.0 (10746)
