### ISSUE TITLE
Beta APP sync is partial

### ISSUE THREAD

**Issue by likevi9528** [bitwarden/android#3407]
### Bitwarden Beta

- [X] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

1. Click "Setting" -> "Other" -> "Sync now"

### Expected Result

Sync data completely.

### Actual Result

Sync data partially.

### Additional Context

I'm judging by the amount of data transferred, I have about 500+ items, so there is noticeable amount of data transferred.
I don't know which synchronization method is better.
 I also report it on #3354.

### Build Version

2024.6.1

### Environment Details

- Device: Redmi k30
- OS: Android 12

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. Can you please try connecting to a different network before attempting to sync your vault again? 

We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, please write us back using our “Contact Support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
