### ISSUE TITLE
"My vault" page is loading for a long time

### ISSUE THREAD

**Issue by likevi9528** [bitwarden/android#3408]
### Bitwarden Beta

- [X] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

_**This can be difficult to reproduce and only happens a few times during a day of heavy use.**_

1. Unlock and enter the APP

### Expected Result

"My vault" page displays items

### Actual Result

The items will not be displayed, the loading state is too long.

### Screenshots or Videos

![81ebeabc67615d7fa7c4c6a2935ead3](https://github.com/bitwarden/android/assets/81839775/f138ec8c-fa28-4714-95d6-c061b5e831f7)

### Additional Context

 I also report it on #3354.

### Build Version

2024.6.1

### Environment Details

- Device: Redmi K30
- OS: Android 12

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. 

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/). This will allow us to gather more information about your account and its usage.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
