### ISSUE TITLE
New logins aren't saved

### ISSUE THREAD

**Issue by jtruland** [bitwarden/android#3543]
### Bitwarden Beta

- [X] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

1. Go to a website needing new login
2. Open BitWarden app and select add new login
3. Generate catch-all email username
4. Generate passphrase
5. Click save

### Expected Result

New, populated vault login entry should exist.

### Actual Result

No login for current site is found. New blank entry is found in vault, which does not contain the new username, password, or uri of the site that was just entered.

### Build Version

2024.7.0

### Environment Details

Samsung Galaxy S23 ultra, one UI 6
Chrome beta

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Adedamola-Aina** [comment]
Hello @jtruland 

I attempted to reproduce what you have described and was unable to do so. I think your error could have its origin in a misconfiguration.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).
You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/).

The issue here will be closed.

Thanks!

**Comment by allmynamesweretakenomoreideas** [comment]
Same here.
Since a few weeks, new entries are empty.

I have analyzed the issue a bit:

1) Adding new entry in App (2024.7.1) --> Entry is shown empty
2) Syncing wit Server --> Entry is shown empty on Web GUI
3) Adding new entry on Web GUI --> Entry is shown and populated on mobile App

It seems the mobile app is not able to write or encrypt the data correctly.

- Logging out an reinstalling of the app does not help

Smartphone is a Samsung S20 FE.
Might this be a Samsung issue?

@jtruland Could you find a solution?
