### ISSUE TITLE
support for saving gpg and ssh keys and genarate them in the app for use

### ISSUE THREAD

**Issue by olumolu** [bitwarden/android#3643]
### Bitwarden Beta

- [X] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

Having this feature helps manaage and save private and public keys and share public key on request where as keepiing private safe with you.
Now coming to next part if you are on a phone or something genarating ssh and gpg keys you need gpg tool but having it in the app helps

### Expected Result

None

### Actual Result

None

### Build Version

6.1

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by cbw23** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/ 

Please sign up on our forums and search to see if this request already exists (https://community.bitwarden.com/signup). If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Note that the “Closed as not planned” status is for internal tracking purposes only, please do not hesitate to send us your suggestions to the forum.

Thanks!

**Comment by olumolu** [comment]
Sure i will.
