### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by Capable-Tea-001** [bitwarden/android#3769]
### Bitwarden Beta

- [X] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

The app will open and I can use autofill once.

As soon as I try to use autofill a second time, the app crashes.

### Expected Result

No crash

### Actual Result

App crash 

### Additional Context

Had to send my pixel 8 to be fixed, so back on my OnePlus Nord2.

The UI looks different, I've been on holiday without WiFi so I suspect the last update from 9th August changed the ui.

### Build Version

Version: 2024.8.0 (18985)

### Environment Details

Nord2 
Version: 2024.8.0 (18985)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by Capable-Tea-001** [comment]
@sammbw what a bullsh*t response. Why don't you try asking for more information rather than just immediately closing the bug?
