### ISSUE TITLE
log in with device, bug

### ISSUE THREAD

**Issue by Bazixv13** [bitwarden/android#3795]
### Bitwarden Beta

- [X] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

1. Go to bitwarden vault site, type your e-mail
2. Click Log in with device
3. Click on notification

### Expected Result

App showing log in prompt

### Actual Result

app crashing every time (tried multiple times)

### Screenshots or Videos

https://github.com/user-attachments/assets/b2dc57ab-5832-499f-96d4-d58fbd674d94

### Additional Context

logs (can't copy)
![Screenshot_2024-08-21-02-49-03-204_com miui bugreport](https://github.com/user-attachments/assets/52d4d457-34f5-47f7-be38-c18a5a007b5a)
![Screenshot_2024-08-21-02-49-06-419_com miui bugreport](https://github.com/user-attachments/assets/cae25c51-f3c6-414e-9528-0c0fc48423e7)

### Build Version

© Bitwarden Inc. 2015-2024  Version: 2024.8.0 (18985)

### Environment Details

Android version: 13
device brand: Xiaomi

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so - this may be specific to your device or network configuration.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
