### ISSUE TITLE
Creating passkey for WhatsApp, it failed successfully

### ISSUE THREAD

**Issue by JasonHK** [bitwarden/android#3808]
### Bitwarden Beta

- [X] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

1. Create a passkey inside WhatsApp

### Expected Result

A passkey was created, WhatsApp congrats you the passkey was created.

### Actual Result

A passkey was created, but WhatsApp doesn’t know the passkey was created, hence “failed successfully”.

### Screenshots or Videos

https://github.com/user-attachments/assets/8751ef46-4d24-41bc-959c-df79cd6f8af5

### Build Version

2024.8.0 (18985)

### Environment Details

- Device: Samsung Galaxy S21 5G
- OS Version: Android 14, One UI 6.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by daniellbw** [comment]
Hi there,

Your issue appears to be describing the intended behavior of the software. 
For Android "while passkeys for web browsers are supported, support for is apps coming soon in a future beta build". : https://bitwarden.com/help/storing-passkeys/#tab-android-(beta)-3XutklkReT3Gw0l1qHhBem


We use GitHub issues as a place to track bugs and other development related issues. 

This issue will now be closed. 

Thanks!

**Comment by MrRoiz** [comment]
Any update on this? I got the same error on current android latest version

**Comment by SaintPatrck** [comment]
Hi all,

Bitwarden successfully processes and responds to the passkey request without issue. We believe this is an bug in WhatsApp's implementation. More details can be found in comment https://github.com/bitwarden/android/issues/4582#issuecomment-2631639765.

Since passkey creation does work during initial sign-in, but not when you are currently signed in, I suggest reporting this behavior to WhatsApp for further investigation.
