### ISSUE TITLE
unable to exit "tabs"

### ISSUE THREAD

**Issue by Bazixv13** [bitwarden/android#3816]
### Bitwarden Beta

- [X] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

1. Log in into bitwarden
2. Click on any of the items in the vault tab (Login, Card, Identity, Secure more, trash, folders
3. click on the vault on the bottom toolbar
4. click on the arrow

### Expected Result

Going to the previous page

### Actual Result

Can't exit the page until using system navigation buttons

### Build Version

© Bitwarden Inc. 2015-2024  Version: 2024.8.0 (18985)

### Environment Details

Android 13

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Adedamola-Aina** [comment]
Hi @Bazixv13 

I attempted to reproduce this issue and was unable to do so.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.
Thanks!
