### ISSUE TITLE
Android: Session timeout lacks "never" optin

### ISSUE THREAD

**Issue by koehntopp** [bitwarden/android#3817]
### Bitwarden Beta

- [X] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

1. Go to 'Settings - Account Security'
2. Click on 'Session Timeout'

### Expected Result

I have an option to say "Never", which is what I've been using on my phone for years

### Actual Result

"Never" is not in the list of options

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/20cbc1ae-b152-4cc1-9b6a-c053cbfca169)

### Additional Context

This leads to annoying logouts whenever I 'just' quickly need to login somewhere 

### Build Version

2024.8.0 (18985)

### Environment Details

Pixel 9 Pro XL

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by TroyBW** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a larger than default font size, and if that is the case, you may need to scroll down the list to see additional options.

If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by koehntopp** [comment]
Thank you - yes, font size seems to be the issue. If you look at the screenshot - the missing scroll bar prevented me from seeing this immediately. Maybe there's a way to add one?

**Comment by Bussersyed** [comment]
https://www.facebook.com/profile.php?id=100078854351734&mibextid=ZbWKwL
