### ISSUE TITLE
No autofill sugestion on specific website

### ISSUE THREAD

**Issue by KevinNitroG** [bitwarden/android#3827]
### Bitwarden Beta

- [X] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

1. Go to https://student.uit.edu.vn/
2. Click on login section

### Expected Result

Autofill suggestion comes up, on GBoard...

### Actual Result

No autofill sugestion

### Screenshots or Videos

![Screenshot_2024-08-25-11-43-57-486_com brave browser](https://github.com/user-attachments/assets/aa98b226-6148-4404-971f-ac195ccd8dd8)

### Build Version

2024.8.0 and 2024.8.1

### Environment Details

- Device: Redmi K30 5G
- OS: MIUI 13.0.5 Android 12

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @KevinNitroG,

We appreciate you letting us know of this. Due to the nature of autofill, we track such reports internally using different forms, depending on the platform:

- Mobile: https://docs.google.com/forms/d/e/1FAIpQLScMopHyN7KGJs8hW562VTzbIGL4KcFnx0wJcsW0GYE1BnPiGA/viewform
- Browser extension: https://docs.google.com/forms/d/e/1FAIpQLSfkxh1w6vK8fLYwAbAAEVhvhMAJwfFNDtYtPUVk1y5WTHvJmQ/viewform

In this case, I have gone ahead and filed a report on your behalf. In the future, if you encounter any other page or application where Bitwarden does not perform autofill as expected, please feel free to use the forms above directly; They are also accessible via the (New issue) button on GitHub.

I will now close this report.

Thank you again,

**Comment by KevinNitroG** [comment]
Thank you @SergeantConfused
