### ISSUE TITLE
Catch all email generator has no option for appending URI as prefix

### ISSUE THREAD

**Issue by Serrated3150** [bitwarden/android#3846]
### Bitwarden Beta

- [X] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

1. Add new item into Bitwarden vault.
2. Fill in the URI with any details.
3. Click on the generate username button.
4. Select Catch-all email from the drop down. 
5. Fill in the domain details. 
6. No additional options for using the URI to generate a username exists.

### Expected Result

An additional dropdown to select randomly generated prefix for the catch all email address or a URI host based prefix should exist.

### Actual Result

No dropdown exists for generating the prefix. The only option is to use a randomly generated prefix.

### Build Version

© Bitwarden Inc. 2015-2024  Version: 2024.8.0 (18985)

### Environment Details

Samsung Galaxy S22
Android 14
One UI 6.1
August Security Patch

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Adedamola-Aina** [comment]
Hi @Serrated3150 

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/ 

Please sign up on our forums and search to see if this request already exists (https://community.bitwarden.com/signup). If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Note that the “Closed as not planned” status is for internal tracking purposes only, please do not hesitate to send us your suggestions to the forum.

Thanks!

**Comment by Serrated3150** [comment]
Hi @Adedamola-Aina,

I disagree that this is a feature request as this functionality is on the main release of the Bitwarden Android app but is not in the beta release of the new Bitwarden Android app. Happy to be corrected but I believe features that are missing in the beta but are available in the main release should count as bugs.
