### ISSUE TITLE
Multiple Autofill failure(s)

### ISSUE THREAD

**Issue by ZethiaZ** [bitwarden/android#3882]
### Bitwarden Beta

- [X] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

1. Go to intave.ac
2. Click on Dash
3. Wait for the page to load and click on the login field

### Expected Result

Inline tile to autofill shows up in keyboard every time.

### Actual Result

I am reporting multiple issues here so I will split them into each:

On Pixel 6a:
The tile is inconsistent and is not always present. Sometimes closing the keyboard and clicking again will have it appear, and sometimes it will simply never work unless I unlock the Bitwarden app.

It never works on a fresh device start until I unlock the Bitwarden app either.

On the Pixel 8:
The inline tray for login is never presented no matter what I do, but when I get to the password field it recognizes it.

### Additional Context

Both devices I have confirmed have working inline autofill on other sites, specifically I tested google.

### Build Version

19099

### Environment Details

Pixel 8:
Bitwarden version 2024.8.1 (19099) (F-Droid version downloaded as an APK) GrapheneOS (Android 14) and Futo Keyboard.

Pixel 6a: Bitwarden version 2024.8.1 (19099) (Downloaded from Play Store Beta program) Stock Pixel OS & Keyboard (Android 14)

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @ZethiaZ,

We appreciate you letting us know of this. Due to the nature of autofill, we track such reports internally using different forms, depending on the platform:

- Mobile: https://docs.google.com/forms/d/e/1FAIpQLScMopHyN7KGJs8hW562VTzbIGL4KcFnx0wJcsW0GYE1BnPiGA/viewform
- Browser extension: https://docs.google.com/forms/d/e/1FAIpQLSfkxh1w6vK8fLYwAbAAEVhvhMAJwfFNDtYtPUVk1y5WTHvJmQ/viewform

Could you please report the URLs you encounter using the relevant form above? Please mention the operating system that you're running on the Pixel 8 as that could be related; I say this because whilst testing this on Android 14 on a Pixel 5, the [Inline autofill](https://bitwarden.com/help/auto-fill-android/#inline-autofill) prompt was shown consistently on the (E-Mail address or Name) field, even whilst Bitwarden 2024.8.0 was locked; I also rebooted the device, launched Chrome, and navigated to that webpage, and I was presented with the Inline autofill prompt in that case as well.

This GitHub report will now be closed.

I thank you in advance for your understanding,
