### ISSUE TITLE
BW APP for Android fails to auto fill using Starts With match detection

### ISSUE THREAD

**Issue by andreaippo** [bitwarden/android#3910]
### Steps To Reproduce

This refers to the BW Android app

1. Leave default match detection as it is
2. Create an entry with a URI that overrides match detection to Starts With, e.g. http://192.168.1.1/myApp
3. Go to http://192.168.1.1/myApp

### Expected Result

BW proposes to autofill

### Actual Result

BW does not propose to autofill

### Screenshots or Videos

![Screenshot_20240911-224338](https://github.com/user-attachments/assets/cb4675e1-8d38-43d2-95af-97bb3c8c43ca)
![Screenshot_20240911-224351](https://github.com/user-attachments/assets/23a6a14d-d347-4056-8817-164e047c4cdc)
![Screenshot_20240911-224411](https://github.com/user-attachments/assets/ef421e08-cd65-49a5-93c7-d0caa1ff96f8)
![Screenshot_20240911-224417](https://github.com/user-attachments/assets/102b9684-2e75-4390-b4b9-c33fbeb0caa4)

### Additional Context

I need Starts with because I don't have just `myApp` hosted on my server, but several ones, each with its login info.

Therefore I need other entries for `myApp2` etc under the same host.

### Operating System

Android

### Operating System Version

Android 14

### Web Browser

Firefox

### Browser Version

130.0

### Build Version

Versione: 2024.8.1 (19099)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there,

Your issue appears to be describing the intended behavior of the software. If you want this to be changed, it would be a feature request.

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. 

Thanks!

**Comment by benkap** [comment]
@sammbw, In what way this is the intended behavior? Using starts-with detection is not supported with auto fill?

**Comment by Naushikha** [comment]
When will this be fixed? 
This issue is mentioned here as well: https://github.com/bitwarden/mobile/issues/1946

**Comment by SaintPatrck** [comment]
Hi all,

The Autofill framework does not provide us the entire URL so we are unable to perform matching on **path** or **port numbers**, which according to the description is the expectation. We do mention this limitation in [Match detection options](https://bitwarden.com/help/uri-match-detection/#match-detection-options) on our Help page. 

We have reported this lack of information to Google and requested the information be made available. As of now, we have not seen any movement on either ticket (https://issuetracker.google.com/issues/413521641 and https://issuetracker.google.com/issues/378464307). 

As a temporary work-around, consider modifying the match type to Host so that at least _partial_ matches are suggested instead of no suggestions showing.

You can also try using the Accessibility Quick Tile. We are often able to get the port and path information via this method because we have the ability to read and parse the screen ourself, instead of relying on the data provided by Android's Autofill API.

Also, feel free to +1 the linked tickets to let Google know it is negatively effecting your autofill experience.

**Comment by kaplanben** [comment]
Anyone knows the behavior with other password manager clients? E.g. Lastpass, keeper? How do they handle this? Does all suffer from the same issue due to the lack of information returned by Android?

**Comment by SaintPatrck** [comment]
@kaplanben, I briefly checked Dashlane and ProtonPass. This appears to be a consistent limitation.

Using https://fill.dev as a test site, I saved two different credentials with two different associated URI's; https://fill.dev/form/login-simple and https://fill.dev/form/registration-email

<img width="365" alt="Image" src="https://github.com/user-attachments/assets/60c874c4-7d39-419c-9aae-b5033aa074ec" />

<img width="365" alt="Image" src="https://github.com/user-attachments/assets/ca2bbc95-95b0-47db-a2e5-172b5dd6273a" />

## Results

I could not locate "match type" options in either app. When I navigate to https://fill.dev/form/login-simple, **both** saved credentials are suggested by both apps, indicating the URI **path** is not respected by either.

### Dashlane:

<img width="365" alt="Image" src="https://github.com/user-attachments/assets/f2b26363-17d7-410e-aa6f-0c19cd2f4190" />

### Proton Pass:

<img width="365" alt="Image" src="https://github.com/user-attachments/assets/203b6bea-6b04-4172-8eac-6f091e56bf8f" />
