### ISSUE TITLE
Visual Bug on App Navigation Bar

### ISSUE THREAD

**Issue by Jetspectre** [bitwarden/android#4014]
### Bitwarden Beta

- [X] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

Click on Settings on the Navigation Bar.

### Expected Result

Outlined Icon will be Filled the moment I select it

### Actual Result

Icon changes from Outlined to Rounded Filled

### Screenshots or Videos

https://github.com/user-attachments/assets/3c84e7b9-d5e9-4786-806f-6acade08be08

### Build Version

2024.9.0 (19209)

### Environment Details

Pixel 7
Android 14 AP2A.240905.003

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. Could you please try updating the app to the latest release (2024.9.2)?

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by Jetspectre** [comment]
Hi @Greenderella, the latest release show beta is only until 2024.9.0 (19209), github and playstore included. I'm assuming it has been fixed in 2024.9.2?
