### ISSUE TITLE
Make capitalization default for fields that normally use it

### ISSUE THREAD

**Issue by antgig** [bitwarden/android#4025]
### Bitwarden Beta

- [x] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

1. Go to Add Item for Login/Card/Identity/Secure note
2. Click on Name
3. Start typing

### Expected Result

First letter of entered text is a capital letter

### Actual Result

First letter is lower case letter

### Additional Context

Fields that should have capitalization enabled by default:

Login
- Name
- Notes
- New custom field -> Name

Card
- Name
- Cardholder name
- Notes
- New custom field -> Name

Identity
- Name
- First name
- Middle name
- Last name
- Company
- Address?
- City/Town
- State/Province
- Country
- Notes
- New custom field -> Name

Secure note
- Name
- Notes
- New custom field -> Name

### Build Version

2024.9.0

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/ 

Please sign up on our forums and search to see if this request already exists (https://community.bitwarden.com/signup). If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Note that the “Closed as not planned” status is for internal tracking purposes only, please do not hesitate to send us your suggestions to the forum.

Thanks!
