### ISSUE TITLE
No app/web icons on inline autofill

### ISSUE THREAD

**Issue by TenSeventy7** [bitwarden/android#4071]
### Bitwarden Beta

- [X] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

1. Open any app (browser/app) that has a login screen
2. Click on the username or password field
3. Wait for autofill suggestions to show up

### Expected Result

Proper app icons or web favicons should show up beside the account's name.

### Actual Result

Only a globe icon appears everytime.

### Screenshots or Videos

![Screenshot_20241011_142437_Samsung Internet](https://github.com/user-attachments/assets/4e22cd31-2ad9-49a1-be27-0f88f31ff12a)
![Screenshot_20241011_142548_Samsung Internet](https://github.com/user-attachments/assets/6f37aeae-7de5-4f09-9eac-16d60cd00fd9)
![Screenshot_20241011_142645_McDelivery PH](https://github.com/user-attachments/assets/81b26d36-26c5-4b96-98c1-d9caea93110a)
![Screenshot_20241011_142700_Via](https://github.com/user-attachments/assets/323a26fa-f9b6-4ab7-8f77-6acc74178a11)
![Screenshot_20241011_142826_McDelivery PH](https://github.com/user-attachments/assets/c2c61770-2544-4193-9279-a609f61ade18)
![Screenshot_20241011_142816_Samsung Internet](https://github.com/user-attachments/assets/6479e54d-ca9c-4242-8188-a6d2ee5733bd)

### Additional Context

I've tested and reproduced the issue from **Samsung Internet** (com.sec.android.app.sbrowser), **McDelivery PH** (ph.mobext.mcdelivery), and **Via** (mark.via.gp). Issue reproduced regardless if **'inline autofill'** is enabled or not.

### Build Version

2024.9.0

### Environment Details

- Device: Samsung Galaxy A35
- OS version: Android 14; One UI 6.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by rmcdowell-bitwarden** [comment]
Hi there,

Your issue appears to be describing the intended behavior of the software. If you want this to be changed, it would be a feature request. You can see examples of this behavior in our documentation here: https://bitwarden.com/help/auto-fill-android/#inline-autofill

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. 

Thanks!
