### ISSUE TITLE
connecting failure error

### ISSUE THREAD

**Issue by openwebkey** [bitwarden/android#4109]
### Bitwarden Beta

- [X] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

2. Click on '...'
3. Scroll down to '...'
4. Click on '...'

### Expected Result

I expectation Not "connecting failure" error message on my Android 6

### Actual Result

![Screenshot_20241017-023608](https://github.com/user-attachments/assets/d1556a8e-283b-47e2-ad56-ca3d88620db2)

### Screenshots or Videos

![Screenshot_20241017-023608](https://github.com/user-attachments/assets/d25f3cc0-92dd-417b-98c7-eae4a01e9112)

### Build Version

lastik github realase

### Environment Details

Zte blade a506 android 6

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by BBGhub** [comment]
Hi There,

The issue you are facing is a result of Let's Encrypt shortening it's chain of trust: https://letsencrypt.org/2023/07/10/cross-sign-expiration.html 

Bitwarden uses a Let's Encrypt certificate for it's services - please note the message on this page that states:

If you use Android 7.0 or earlier, you may need to take action to ensure you can still access websites secured by Let’s Encrypt certificates. We recommend installing and using Firefox Mobile, which uses its own trust store instead of the Android OS trust store, and therefore trusts ISRG Root X1.

You could explore the option of installing the ISRG Root X1 certificate in the Android OS trust store, though this is something I am not able to assist you with myself. We recommend accessing your Bitwarden vault using the Firefox Mobile browser via https://vault.bitwarden.com or https://vault.bitwarden.eu at this time.

If you have any further questions, please don't hesitate to ask.

As a side note, the minimum Android version for the mobile app will be raised to 9.0 when the native build is released.
