### ISSUE TITLE
Bitwarden loads the vault infinitey

### ISSUE THREAD

**Issue by Ehab-d** [bitwarden/android#4208]
### Bitwarden Beta

- [X] I'm using the new native Bitwarden Beta app and I'm aware that legacy .NET app bugs should be reported in [bitwarden/mobile](https://github.com/bitwarden/mobile)

### Steps To Reproduce

1. Go to the menu
2. Click on Lock
3. Unlock the vault

### Expected Result

The vault content should load normally.

### Actual Result

Bitwarden loads the vault infinitely.

### Screenshots or Videos

https://github.com/user-attachments/assets/3ba83c45-90b1-46f8-80c4-14207c32eb98

### Additional Context

- Autofill also cannot be done because this behavior occurs when selecting an account from the autofill menu.

- The vault is not loaded unless I press Sync manually.

### Build Version

v2024.10.2 (19397)

### Environment Details

- OPPO A15
- Android 10

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by daniellbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a misconfiguration.

Please try reinstalling the Bitwarden app by following the below steps:

 -  Uninstall the Bitwarden client
 -  Restart the device (perform a full power cycle, shutting the device down completely and then restarting it)
 -  Reinstall Bitwarden from the Play Store

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by Aer3x** [comment]
same here, keeps loading on android.

**Comment by Ehab-d** [comment]
> same here, keeps loading on android. latest update

They were unable to reproduce the issue, so they rejected its existence in the first place and closed the issue -_-

**Comment by singhh9596** [comment]
+1

**Comment by fessmm** [comment]
See https://github.com/bitwarden/android/pull/4214

**Comment by dfunkt** [comment]
This is the original issue for the problem mentioned above -> https://github.com/bitwarden/android/issues/3881
