### ISSUE TITLE
The New item icon "+" its no't  showing in folder 

### ISSUE THREAD

**Issue by maxmini1** [bitwarden/android#4246]
### Steps To Reproduce

1. Go to 'open the app'
2. Click on 'vault tap'
3. Scroll down to '..folder.'
4. Click on 'open it'

### Expected Result

You should see the "+" icon to create new item

### Actual Result

The "+" icon its not showing here, you have to go to back to the main vault to create new item

### Screenshots or Videos

![Screenshot_20241106_182617_Bitwarden Beta](https://github.com/user-attachments/assets/0c2a010f-a7e8-4d9e-9084-fb10453e746e)

### Additional Context

In the previous version of the ( non native app )
You can create new item inside folder 

### Build Version

Version: 2024.11.1 (19422)

### What server are you connecting to?

US

### Environment Details

Device SAM-A15
OS : android 14

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by cbbit** [comment]
Hi there,

Your issue appears to be describing the intended behavior of the software. In the Vaults view, click the + icon to create a new item. In the new item creation window, you can assign the item to a specific folder. If you want this to be changed, it would be a feature request.

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. 

Thanks!
