### ISSUE TITLE
The new "beta" version dosen't launch some apps

### ISSUE THREAD

**Issue by maxmini1** [bitwarden/android#4277]
### Steps To Reproduce

1.Onpe bitwarden app
2.Tap login section (s)
3.Select item e.g facebook 
4.launch the app via package name (com.facebook.katana)

### Expected Result

BW should take me to play store to install that app
Or just open it if its install already

See here https://github.com/bitwarden/android/pull/4233

### Actual Result

BW open the app package name in the browser
_________

### Screenshots or Videos

https://github.com/user-attachments/assets/369bfa9d-1c3f-4e1d-8496-5e0d56004093

### Additional Context

I have test many apps , and its work fine, except
Github (com.github.android)
Facebook (com.facebook.katana)
Threads (com.instagram.barcelona)
Instagram (com.instagram.android)
Linkedin (com.likedin.android)
Reddit (com.reddit.frontpage)
X Twitter (com.twitter.android)  "NOTICE" i try install X twitter and launch it from BW, didin work!

### Build Version

Version: 2024.11.4 (19444) beta "Google play"

### What server are you connecting to?

US

### Environment Details

Device: SAM-A15
OS: Android 14

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by maxmini1** [comment]
You have to add "androidapp://"  before the package names.

**Comment by sammbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a misconfiguration of the URI value - please prefix with 'androidapp://' ahead of the package's name.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
