### ISSUE TITLE
Search function does not retrieve notes content

### ISSUE THREAD

**Issue by Vstory** [bitwarden/android#4340]
### Steps To Reproduce

1. Create a new entry, enter a username, password, and notes, then save.
2. Use the search function to search for any characters in the note you entered, and you will get empty search results.

### Expected Result

Use the search function to search for any characters in the note you entered, and you will get empty search results.

### Actual Result

Search notes not working.

### Additional Context

The note contains some very important information. When there are too many password entries, you can't expect users to flip through the password entries one by one and find the password entry with the corresponding note information.

**Search functionality should be able to retrieve note information.**

### Build Version

2024.11.5

### What server are you connecting to?

US

### Environment Details
```
[Device Brand]: Xiaomi
[Device Model]: M2102K1AC
[Display]: TKQ1.220829.002 test-keys
[Android Version]: 13
[Android API Level]: 33
[System Locale]: zh_CN
[CPU ABI]: arm64-v8a
```
### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Vstory** [comment]
Ok

**Comment by rmcdowell-bitwarden** [comment]
Hi there,

This behavior is the intended behavior of the search function. Currently, the Bitwarden mobile applications only support the "basic search" functionality. You can find more information here: https://bitwarden.com/help/searching-vault/#basic-search

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
