### ISSUE TITLE
New Interface - Cannot differentiate between 0 and O

### ISSUE THREAD

**Issue by ToddCrimson** [bitwarden/android#4350]
### Steps To Reproduce

1. Go to view password or secret (or anywhere on bitwarden app on Android)
2. Click on anything that has 0 or O stored 
3. Scroll down to view it 
4. Click on unhide 

So the new interface is great, except you are extremely hard pressed to tell if it is a 0 or O ...

### Expected Result

I would like clear differentiation between those two. Maybe a diagonal line through zero? Previous interface, we had no issues.

### Actual Result

Extremely difficult to tell difference between 0 and O

### Screenshots or Videos

![IMG_20241121_074426](https://github.com/user-attachments/assets/25fd46ab-5f3a-4a97-b345-351d74fd5b6d)

### Build Version

Version: 2024.11.3 (19432)

### What server are you connecting to?

US

### Environment Details

Pixel 8 Pro with latest OS

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by jtodddd** [comment]
Hi there,

Your issue appears to be describing the intended behavior of the software. If you want this to be changed, it would be a feature request.

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. 

Thanks!

**Comment by ToddCrimson** [comment]
This is not a feature request. You must be kidding me.
Have you read it? 
It is a REGRESSION therefore a BUG.
It didn't act this way before. 

You cannot claim this a feature request and close this. 
This is a BUG. 
I am unable to differentiate between ZERO and the alphabet "Capital O" in your new design interface.

Please ACKNOWLEDGE that it wasn't happening before. You could easily differentiate .


And please for the love of all that is sane and nice, don't dismiss it just because you want to have less open issues !!!
