### ISSUE TITLE
Update to version 2024.11.6 (19499) "lost" all vault data

### ISSUE THREAD

**Issue by RickPJ** [bitwarden/android#4367]
### Steps To Reproduce

Update to version 2024.11.6 (19499) via Play Store

### Expected Result

App should run correctly as before

### Actual Result

All vaults were empty, both personal and shared organisation

### Additional Context

The only action that recovered the vault was to delete all app data via Android settings (effectively app re-install), and login again from scratch. After that it was back to normal.
I don't know if this was a random glitch on my device or if it's a general problem. If the latter, it will be a support nightmare!

### Build Version

2024.11.6 (19499)

### What server are you connecting to?

US

### Environment Details

Fairphone 3+, AOS 11

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Zoarial94** [comment]
I also experienced this issue. I only discovered the issue this morning, and I am on 2024.11.6 from GitHub directly. I was able to resolve the issue by logging out and back in. 

I'm guessing the issue occurred a few days ago, and I only noticed today. What is notable is that I only had a single login listed, and it was one that I added yesterday. 

Syncing the vault did not delete all the accounts since I was able to log out and back in to recovee everything.

**Comment by Bazixv13** [comment]
Noticed the same issue syncing the vault from the app setting didn't solve the problem I had to log out and log back maybe this occured because of autofill in not sure but it happened after clicking the autofill bitwarden in keyboard
app version: 2024.11.6
