### ISSUE TITLE
crashed and could not be logged in

### ISSUE THREAD

**Issue by qwerttvv** [bitwarden/android#4393]
### Steps To Reproduce

1. enter my mail
2. enter password
3. enter 2FA code
4. Show "logging in"
5. app crashed

### Expected Result

Login and use

### Actual Result

crashed

### Additional Context

app crashed but i'll get an email alert that a new device has logged in.

2024.11.5 (19461)[com.x8bit.bitwarden-fdroid.apk](https://github.com/bitwarden/android/releases/download/v2024.11.5/com.x8bit.bitwarden-fdroid.apk) 
and 
2024.11.6 (19499)[com.x8bit.bitwarden-fdroid-release.apk](https://github.com/bitwarden/android/releases/download/v2024.11.6/com.x8bit.bitwarden-fdroid-release.apk)
and
2024.11.3 (19432)[com.x8bit.bitwarden-fdroid.apk](https://github.com/bitwarden/android/releases/download/v2024.11.3/com.x8bit.bitwarden-fdroid.apk)
and
2024.11.1 (19422)[com.x8bit.bitwarden-fdroid.apk](https://github.com/bitwarden/android/releases/download/v2024.11.1/com.x8bit.bitwarden-fdroid.apk)
and
2024.10.2 (19397) [com.x8bit.bitwarden-fdroid.apk](https://github.com/bitwarden/android/releases/download/v2024.10.2/com.x8bit.bitwarden-fdroid.apk)
and
2024.10.1 (19388)[com.x8bit.bitwarden-fdroid.apk](https://github.com/bitwarden/android/releases/download/v2024.10.1/com.x8bit.bitwarden-fdroid.apk)

they all failed.

i've tried uninstalling the programme and reinstalling it
it still crashes...

i tried downloading the latest version 2024.10.0 (11270) from google play and it works fine!

### Build Version

2024.11.5 (19461)

### What server are you connecting to?

US

### Environment Details

android 13

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by rmcdowell-bitwarden** [comment]
Hi there,

I attempted to reproduce your issue with each of these Bitwarden versions using my own Android 13 device an and was unable to do so.

Could you please try reinstalling the Bitwarden app by following the below steps:

 -  Uninstall the Bitwarden client
 -  Restart the device (perform a full power cycle, shutting the device down completely and then restarting it)
 -  Reinstall Bitwarden from the download link below

 Bitwarden Downloads: https://bitwarden.com/download

This will clear any cached data that may be impacting your installation of the Bitwarden application.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
