### ISSUE TITLE
Latest versions are not available on play store

### ISSUE THREAD

**Issue by trlef19** [bitwarden/android#4398]
### Steps To Reproduce

I think latest version on play store is 2024.10

### Expected Result

Latest version is available for download

### Actual Result

2024.10 is the latest one

### Build Version

Doesnt matter

### What server are you connecting to?

EU

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by vdb86** [comment]
Yeah I've been waiting on the new version for 3 weeks now and it's still not available on the Google Playstore.

**Comment by rizi** [comment]
> Yeah I've been waiting on the new version for 3 weeks now and it's still not available on the Google Playstore.

Same here...

**Comment by rmcdowell-bitwarden** [comment]
Hi there,

The new version of the Android app is currently in a staged rollout and will eventually be available for all users through the Google Play Store. If you would like to download the new version of the app now, you can find it on our GitHub repository here: https://github.com/bitwarden/android/releases

We use GitHub issues as a place to track bugs and other development related issues.

The issue here will be closed.

Thanks!
