### ISSUE TITLE
Cannot autofill on adp website (which the app redirects to)

### ISSUE THREAD

**Issue by nitrocode** [bitwarden/android#4407]
### Steps To Reproduce

1. Open the adp app and tap login
    - this brings you to https://m.online.adp.com/signin/v1/?transaction_id=snip&returnURL=https://m.online.adp.com/oauth/client/v3/ADPMobile%3Frun%3Dtrue&TARGET=https://m.online.adp.com/oauth/client/v3/ADPMobile/auth
3. Click on password
4. Notice auto fill doesn't work even with adp.com or m.mobile.adp.com sites added to the cred

Auto fill works fine on other sites on mobile

Tested on Firefox Mobile

### Expected Result

Auto fill works on the adp website

### Actual Result

Autofill does not work

### Screenshots or Videos

n/a

### Additional Context

- original issue https://github.com/bitwarden/clients/issues/12195

### Operating System

Android

### Operating System Version

android 14

### Web Browser

Firefox

### Browser Version

firefox 133

### Build Version

2024.10.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by daniellbw** [comment]
Hi there!

We appreciate you letting us know of this issue. Due to the nature of autofill issues, we track them internally using different Forms depending on the platform:

mobile: https://docs.google.com/forms/d/e/1FAIpQLScMopHyN7KGJs8hW562VTzbIGL4KcFnx0wJcsW0GYE1BnPiGA/viewform

browser extension: https://docs.google.com/forms/d/e/1FAIpQLSfkxh1w6vK8fLYwAbAAEVhvhMAJwfFNDtYtPUVk1y5WTHvJmQ/viewform

Could you please proceed and fill out the relevant form in order to report this directly to the Bitwarden Engineering team?

In the future, if you encounter any other page or app that doesn't autofill as expected, please avoid opening a new GitHub issue and go directly to the corresponding form.

This issue will now be closed. 

Thanks!
