### ISSUE TITLE
Bitwarden App Android: can not see top and bottom by new entry

### ISSUE THREAD

**Issue by Clemens-Ratte-Polle** [bitwarden/android#4412]
### Steps To Reproduce

By making a new or editing an entry in Bitwarden and put some info text to the lower notes box, i can not scroll to the top and not to the bottom, because the keyboard app hides or blocks it partly. See screenshot.
Only when clicking down the keyboard i can see them.
Feature or Error?

Keyboard Gboard App from Android FairPhone 5 original.
Bitwarden Version: 2024.10.0 (11270)

![Screenshot_20241203-174309](https://github.com/user-attachments/assets/c40c9000-3782-4394-ad0e-d45efe4b56a5)

### Expected Result

See top and downmost infos

### Actual Result

Not able to see top or bottom text

### Build Version

: 2024.10.0 (11270)

### What server are you connecting to?

US

### Environment Details

Fairphone 5

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by MarikaBW** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could be device specific and not related to the Bitwarden application.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
