### ISSUE TITLE
No Way to Revert UI to Black

### ISSUE THREAD

**Issue by ItsRogueRen** [bitwarden/android#4429]
### Steps To Reproduce

1. Go to settings
2. Click on appearance

### Expected Result

An option for a black UI, not Material You 

### Actual Result

Only gives an option for Light more or all blue

### Additional Context

Material You looks absolutely disgusting in dark mode. A proper black is needed.

### Build Version

2024.11.7

### What server are you connecting to?

US

### Environment Details

Moto G Stylus 5G 2023, Android 14

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by cbbit** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/ 

Please sign up on our forums and search to see if this request already exists (https://community.bitwarden.com/signup). If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Note that the “Closed as not planned” status is for internal tracking purposes only, please do not hesitate to send us your suggestions to the forum.

Thanks!

**Comment by ItsRogueRen** [comment]
> Hi there,
> 
> Your issue appears to be describing the intended behavior of the software. If you want this to be changed, it would be a feature request.
> 
> We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  
> 
> Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.
> 
> This issue will now be closed. 
> 
> Thanks!

How is it not a bug that a setting that used to be there is now missing?

**Comment by NicholasFlamy** [comment]
As this is a regression and not a feature request, I believe that this issue should be reopened.
