### ISSUE TITLE
"Bitwarden isn't responding" dialog is displayed upon opening the app

### ISSUE THREAD

**Issue by johndoe432** [bitwarden/android#4445]
### Steps To Reproduce

1. Open the app
2. Unlock the vault
3. Android shows "Bitwarden isn't responding" dialog
4. Keep on using the app just by clicking "Wait" in the dialog window

### Expected Result

No window should be present, because the app is responding and is fully working 

### Actual Result

Android keeps showing the dialog window

### Build Version

2024.11.7

### What server are you connecting to?

EU

### Environment Details

- Device: Google Pixel 6a
- OS: Android 15, Build AP4A.241205.013

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by NovaSilentium** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. You may want to check your Kdf settings and update accordingly.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
