### ISSUE TITLE
New Android version do not work with self-hosted

### ISSUE THREAD

**Issue by freQniK** [bitwarden/android#4492]
### Steps To Reproduce

Downloaded 11.5 release get empty screen (does not sync)
Downloaded release from September , same thing.

I have to go back to 2024.5.1 for Bitwarden to actually work with my self hosted server. Certs are fine, desktop versions work beside the very annoying lag (desktop freezes for 1 minute when on VPN with self hosted. I opened an issue about this. Guy didn't believe me. So I created a video proving to him there is a 1 minute freeze every time I open the app when on a VPN. He didn't care and never responded.)

Anyhow, y'all broke something.

# Version 2024.11.5 & 2024.9.1

![IMG_20241218_215135_839_100856](https://github.com/user-attachments/assets/22a1f32f-7996-49e7-b336-251cbfad4580)

# Version 2024.5.1 

![IMG_20241218_220630_376_100725](https://github.com/user-attachments/assets/2805587c-e9ae-4370-9002-f3129a25867a)
![IMG_20241218_220802_938_100815](https://github.com/user-attachments/assets/82d60e3b-002e-493a-a3f6-aa1d24894b26)

### Expected Result

That it would work

### Actual Result

Nada. Bupkis. Zilch. Zero. Nil. Naught. 

### Build Version

2024.11.5

### What server are you connecting to?

Self-host

### Self-host Server Version

Latest

### Environment Details

Graphene, Pix Six

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by BBGhub** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a misconfiguration in the server.

Vaultwarden introduced support for native mobile apps in version 1.31.0. If you’re using native mobile apps and a version of vaultwarden prior to 1.31.0, you will receive an error and should ugrade your server.
https://bitwarden.com/help/hosting-faqs/#q-do-bitwarden-client-apps-support-non-official-servers

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
