### ISSUE TITLE
Android Tray Shortcut no longer working

### ISSUE THREAD

**Issue by sunnylea0** [bitwarden/android#4499]
### Steps To Reproduce

1. Go to notification tray 
2. Click on Autofill

### Expected Result

Bitwarden fills in the login

### Actual Result

Nothing 

### Screenshots or Videos

![Screenshot_20241220-124605](https://github.com/user-attachments/assets/9a7f2b08-a674-473f-8a17-58b5cb680e82)

### Build Version

2024.10.0

### What server are you connecting to?

US

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by jtodddd** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. 

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
