### ISSUE TITLE
Bitwarden doesn't automatically copy TOTP for the PayPal mobile app

### ISSUE THREAD

**Issue by douglasparker** [bitwarden/android#494]
There are two scenarios where this does not work.

First, when the PayPal mobile app has fingerprint login enabled, it requests your TOTP code right after fingerprint verification. I don't know any other app that works this way, so I imagine Bitwarden doesn't support that functionality.

The second scenario is when I am given the option to hit cancel for the fingerprint login, and then I am given a username and password prompt. Bitwarden can autofill these just fine using both the accessibility service and the autofill framework. However, afterwards there is a TOTP prompt and Bitwarden doesn't seem to copy anything again.

**Comment by kspearrin** [comment]
Regarding #2:

There is a known issue where TOTP is not copied to clipboard when using the autofill framework service, however, the accessibility service autofill should copy the TOTP to clipboard if you are a premium member. Can you please reconfirm that with the accessibility service?

**Comment by DougParker1992** [comment]
The accessibility service doesn't seem to show in my notifications for the PayPal app.

**Comment by kspearrin** [comment]
@DougParker1992 I just tested the PayPal app and was able to autofill with accessibility service as expected. I am not sure why you would not receive the notification.

**Comment by DougParker1992** [comment]
> @DougParker1992 I just tested the PayPal app and was able to autofill with accessibility service as expected. I am not sure why you would not receive the notification.

To reproduce this you need to have both TOTP and fingerprint login enabled in the PayPal app. Once both are enabled, completely close the PayPal app and follow these steps.

1) Open the PayPal app. You will be presented with the fingerprint login prompt.
2) Since the auto copying of your TOTP code doesn't work after scanning your fingerprint, hit cancel to be given your username / password login prompt.

At this point, the accessibility service fails to show in your notifications bar. At least immediately... It comes back when clicking around but goes away again. It's extremely inconsistent.

**Comment by anstosa** [comment]
> There is a known issue where TOTP is not copied to clipboard when using the autofill framework service

@kspearrin do you have a link to this issue? I'd like to follow it

**Comment by kspearrin** [comment]
@anstosa https://github.com/bitwarden/mobile/issues/448

**Comment by DougParker1992** [comment]
I'm assuming this could be related to issue #489

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/494
