### ISSUE TITLE
Offline mode not detected in timely fashion while saving with internet blocked by captive portal

### ISSUE THREAD

**Issue by mwisnicki** [bitwarden/android#682]
I was on the airplane setting up new user for the captive portal (WiFi on but restricted internet) and generated new password with bitwarden. Since saving was taking forever I switched to browser and continued signup.

Later on I couldn't find new account in BW.

**Comment by kspearrin** [comment]
This is expected since modifying the vault offline is not supported. You should have received an error message if the app detects you are in airplane mode though. I guess that didnt work?

**Comment by mwisnicki** [comment]
I didn't go back to Bitwarden so it was probably killed by the system at some point and the message with it. I think the app should detect offline faster, I waited about a minute looking at "saving..."  before I switched away.

I hope full offline mode is something in the plans?

**Comment by mwisnicki** [comment]
Found the request for offline mode: https://community.bitwarden.com/t/offline-management-of-writeable-vault-items/107

So let's focus on the better offline detection/error in this ticket.

**Comment by bencgreen** [comment]
+1 for better offline detection.

My setup is as follows:

 - self-hosted BitWarden using docker on a QNAP NAS
 - nginx proxy server operating on a Raspberry Pi
 - ports 80 and 443 forwarded to Raspberry Pi by router (to provide valid SSL certificates and access via a domain name rather than an IP address)
 - proxy server denies access except to local IPs

Everything works brilliantly - I moved from LastPass, and your software is IMHO vastly superior to theirs.  However there is an issue in the iOS app.

Context (1): phone in airplane mode
 - action: try to create new entry
 - result: app says that it needs internet access, so refuses to save item

Context (2): phone with internet access but *outside* home network
 - action: try to create new entry
 - result: app allows save button to be pressed, closes entry as if it has saved the item, but the item is not in the vault afterwards

The same happens when editing items.

Suggestion:
 - rather than check for general internet connection, attempt connection to BitWarden server / api
 - if any status other than 200, act as though there is no internet connection

That way avoids the step of editing an item, and thinking it has saved, when it hasn't.

Of course, I could stop nginx allowing only local access, but I would prefer to keep access local only for security reasons.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/682
