### ISSUE TITLE
Sync in iOS app not working

### ISSUE THREAD

**Issue by danielwagn3r** [bitwarden/android#723]
Sync in the iOS app seem's to be not working, Following environment:

Server: 1.32.0
Phone 1: iPhone 11 w/ iOS 13.3.1; Bitwarden app 2.2.5
Phone 2: OnePlus 2 w/ LineageOS 16.0; Bitwarden app 2.2.8

I've added an item in the web app and tried to sync both phones. While on the OnePlus 2 the item shows up, on the iPhone the app says no item found. A manual sync in the app doesn't resolve the problem.

Furthermore I've tried to add an item on both phones. On OnePlus 2 everything worked as expected. On iPhone the item disappeared (seemingly after a sync) and the app said "no items" again. While the item added on iPhone was visible on web app and Android phone.

**Comment by kspearrin** [comment]
Have you tried logging out and back in on the iPhone? Maybe the session is corrupted.

**Comment by danielwagn3r** [comment]
Hi, I've already tried that. Didn't change anything. In the app I didn't recognize any error or warning, which would indicate there is a problem.

**Comment by danielwagn3r** [comment]
I've tried do reinstall the app and start over from scratch, and syncing works now.

Should there be some kind of feedback, if the sync doesn't work?

**Comment by piyush97** [comment]
Still not working!

**Comment by frickenate** [comment]
This appears to be the same issue as #457. Apparently the latest iOS app version is supposed to be 2.2.6 that has a related fix? But most of us, in many different countries (UK, Poland, Canada, etc.) are on 2.2.5 for months without this supposed 2.2.6 that was released in October?

@kspearrin If iOS is supposed to be at version 2.2.6 instead of 2.2.5, you need to revisit your App Store release procedure. You are *not* releasing your app in all Apple regions properly. I don't know exactly how it works, but I do know you need to select and/or submit to each region. Perhaps you're only releasing to US region, because Bitwarden in other regions is on version 2.2.5 from 5 months ago.

**Comment by sjatkins** [comment]
I am on ios 15.6 and bitwarden is not syncing.  Totally unacceptable for a password manager app.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/723
