### ISSUE TITLE
Most recent Android app update broke "Host" URI detection

### ISSUE THREAD

**Issue by IamGimli** [bitwarden/android#803]
I have a few web sites where different services are available on different ports, each with their own username/password combination. In order for Bitwarden to recognize each interface differently, I have to set the URI detection method to "Host" for those web sites, this way https://mywebsite.com:8080 is recognized separately from https://mywebsite.com:9080 and https://mywebsite.com:7080. 

This works well with the Chrome addon and it used to work well in the Android app, until the last update. Now, on Android, site entries in Bitwarden that have a "Host" type URI detection mechanism are no longer associated with the appropriate app. Bitwarden states that no site has been found for that web site. If I search for the right entry and select "Fill and save", it creates a new URI for that entry with the default "Base domain" detection, which doesn't see the difference between port numbers. If I change the URI detection for that new entry to "Host", then Bitwarden no longer associates it with the web site again. 

## Environment

- Device: Umidigi X and Mi Pad 4
- Operating system: Android 9
- Build Version (go to "Settings" → "About" in the app): 2.3.1 (2257)
- Is this a Beta release? N

**Comment by wqk317** [comment]
This also happened after I updated the beta version of the Google play store today

In addition, I also lost my login data, because I was usually asked to enter my password, but this time I was asked to enter my account and password, just like I just installed the app.

**Comment by IamGimli** [comment]
Just to be clear, I am not in the Beta and the release version I am running (2.3.1 (2257)) shows this issue.

**Comment by jpabloud** [comment]
I had the same problem with latest build (2276) from the Play store, proceeded to delete cache and data and then the app crashed at start.

Uninstalled and installed build 2257 from apkmirror and works fine.

**Comment by locklifter** [comment]
I have the same problem.

**Comment by mportune-bw** [comment]
@IamGimli It looks like the autofill service isn't providing us with the port number, only ` https://mywebsite.com`.  That's why host matching isn't returning anything.  It does however work with the autofill accessibility service - perhaps that's why you experienced it working previously?  

Unfortunately I don't see anything we can do at this time.  A potential workaround could be to use default matching to return all `mywebsite.com` items, and customize the name of each entry to make it identifiable.  Not ideal, but less painful than manual copy/paste IMO.

**Comment by IamGimli** [comment]
I don't understand what you're saying. Under Android Accessibility setting, the Bitwarden autofill service is still enabled. If that's supposed to word, I can confirm it doesn't. 

As for "Unfortunately I don't see anything we can do at this time" does that mean that the loss of that functionality was intentional? If it wasn't, the changes that were should be reversed until you figure out how not to cripple the app's functionality.

**Comment by mportune-bw** [comment]
@IamGimli That's correct, in recent builds the accessibility overlay yields to the autofill overlay since autofill is technically "the right one" and we don't want to unintentionally interfere with it.  However that clearly doesn't help you since autofill fails to pass us the port numbers needed for host matching to work as expected.  I'm re-opening this issue for my own visibility while I ponder options.

**Comment by IamGimli** [comment]
Awesome, thank you!

**Comment by Epirr** [comment]
I'm having the exact same problem on my Android phone.

For example, I have two services. One on http://192.168.1.198:8080/ and the other on http://192.168.1.198:8989/.

I have an entry for each of them in Bitwarden, with the "Host" URI detection type.

Lets say I go to http://192.168.1.198:8080/ on my PC (Chrome). The Bitwarden browser extension correctly identifies the host **and** the port, so it only returns the credentials for the 8080 service. However if I try to do the exact same thing on my Android phone (Tried both Chrome and Samsung Internet), I press the inline Bitwarden vault button in my keyboard to go to the vault, and it says: "There are no items in your vault for 192.168.1.198.".

So it looks like the port isn't being passed over to the Bitwarden app and I'm not sure how to fix this. I don't want to disable autofill as I find it very useful for everything else, it's just when I try to access these services that it becomes an issue.

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/803
