### ISSUE TITLE
Exclude autofill activity from recent

### ISSUE THREAD

**Issue by larena1** [bitwarden/android#893]
The autofill activity should be excluded from recents as it causes issues especially on Android 10 with gesture navigation where you swipe right to switch to the last app. It will reopen the autofill activity then. 

There's an attribute that can be added to the manifest for the activity.

https://developer.android.com/guide/topics/manifest/activity-element#exclude

**Comment by larena1** [comment]
ping @kspearrin @mportune-bw

**Comment by larena1** [comment]
Can you look into this maybe @mportune-bw? It's really annoying and quite a simple fix.

**Comment by ristein** [comment]
+1 here.
I would love this feature.
Bitwarden does not need to appear in recents at all, especially if it is opened from autofill.
Many people including me have the habit to swipe apps out of recents, it is just unnecessary to also have to swipe Bitwarden here since it doesn't change anything.
Also when multitasking back and forth its annoying to have this in between

**Comment by ristein** [comment]
this would be really great

**Comment by larena1** [comment]
@mportune-bw @kspearrin is there anything we can do to help you fix this? This was reported almost 10 months ago

**Comment by vvolkgang** [comment]
Issue migrated to https://github.com/bitwarden/mobile/issues/893
